apiVersion: v1
kind: Secret
metadata:
  name: hce-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres123"
  DB_PASSWORD: "postgres123"
  SPRING_DATASOURCE_PASSWORD: "postgres123"
  JWT_SECRET_KEY: "tu-clave-secreta-super-segura-cambiar-en-produccion-2024"
