apiVersion: v1
kind: Service
metadata:
  name: hce-middleware-service
  namespace: default
  labels:
    app: hce-middleware
spec:
  type: LoadBalancer
  selector:
    app: hce-middleware
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080
  sessionAffinity: ClientIP
